### ISSUE TITLE
Header file and compilation issues with Sophus

### ISSUE THREAD

**Issue by rkeatin3** [uzh-rpg/rpg_vikit#23]
System info:
- Ubuntu 16.04 with ROS Kinetic Kame
- GCC version 5.4.0
- Eigen 3.2.92
- Sophus install with package ros-kinetic-sophus

I am having a few issues compiling with Sophus. First (as a previous issue brought up), I only see .hpp files in my Sophus installation whereas vikit includes the as .h files.

Secondly, there seem to be conflicting typedefs/using declarations when I modified the include directives. I get a number of errors regarding use of type "Matrix", problems with missing template arguments for Sophus types, etc.

Are there specific versions of Sophus or Eigen I should be using?

**Comment by simonreich** [comment]
I managed to build commit from Dec 3rd, 2015, 10871da6d84c8324212053c40f468c6ab4862ee0 using the following packages:

From Ubuntu repository
- Ubuntu 14.04
- ROS Indigo
- GCC 4.8.4
- Eigen 3.2.0

From Sophus upstream https://github.com/strasdat/Sophus
- commit from Feb 7th, 2013, e656ebcd3441d7d89fe6380a093df2cd7ee441c5
