### ISSUE TITLE
compile issue: unable to locate package Sophus

### ISSUE THREAD

**Issue by rnunziata** [uzh-rpg/rpg_vikit#27]
I installed ros-kinetic-sophus
However when compiling vikit I get the following error

Errors     << vikit_common:check /home/rjn/catkin_ws/logs/vikit_common/build.check.004.log
CMake Error at /home/rjn/catkin_ws/src/rpg/rpg_vikit/vikit_common/CMakeLists.txt:26 (FIND_PACKAGE):
  By not providing "FindSophus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Sophus", but
  CMake did not find one.

  Could not find a package configuration file provided by "Sophus" with any
  of the following names:

**Comment by rnunziata** [comment]
miss understanding when installing rpg_open_node

**Comment by IaroslavS** [comment]
> miss understanding when installing rpg_open_node



> I installed ros-kinetic-sophus However when compiling vikit I get the following error
> 
> Errors << vikit_common:check /home/rjn/catkin_ws/logs/vikit_common/build.check.004.log CMake Error at /home/rjn/catkin_ws/src/rpg/rpg_vikit/vikit_common/CMakeLists.txt:26 (FIND_PACKAGE): By not providing "FindSophus.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Sophus", but CMake did not find one.
> 
> Could not find a package configuration file provided by "Sophus" with any of the following names:

How did you solve this problem ?
